export DAGSTER_HOME=~/dagster_home
export HOMEBREW_BUNDLE_FILE=~/dotfiles/homebrew/brewfile
export DOCKER_DEFAULT_PLATFORM=linux/amd64
# TODO: remove once node 17 issues are resolved
# https://github.com/webpack/webpack/issues/14532
# export NODE_OPTIONS=--openssl-legacy-provider
export ANDROID_HOME=/Users/rupertdeese/Library/Android/sdk

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# for homebrew
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/opt/mysql-client/bin:$PATH"
