export DAGSTER_HOME=~/dagster_home
export HOMEBREW_BUNDLE_FILE=~/dotfiles/homebrew/brewfile
export DOCKER_DEFAULT_PLATFORM=linux/amd64
# TODO: remove once node 17 issues are resolved
# https://github.com/webpack/webpack/issues/14532
# Testing removal to see if it works (1/21/2024)
# export NODE_OPTIONS=--openssl-legacy-provider
export ANDROID_HOME=/Users/rupertdeese/Library/Android/sdk

# for homebrew
export PATH=/opt/homebrew/bin/:$PATH

# pyenv
eval "$(pyenv init --path)"
